config/routes.rb
Nrblog::Application.routes.draw do |map|
  devise_for :authors, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  scope '(/:locale)', :constraints => { :locale => /\w{2}/ } do
    controller :home do
      get '/' => :index, :as => :index
    end

    controller :sitemap do
      get '/sitemap.xml' => :index, :as => :sitemap
    end

    scope '/admin' do
      resources :categories, :except => :show
      resources :menu_items, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :images
      resources :blocks, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :tags, :except => :show
      resources :contents, :except => :show do
        delete '/:aid' => :destroy_attachment, :as => :destroy_attachment, :on => :member
        get '/add_attachment' => :add_attachment, :as => :add_attachment, :on => :collection
        post '/preview' => :preview_content, :as => :preview_content, :on => :collection
      end
    end

    controller :categories do
      scope '/' do
        get '/:url_alias' => :show, :as => :show_category
      end
    end
    controller :tags do
      scope '/tags' do
        get '/:tag' => :show, :as => :show_tag
      end
    end
    controller :contact do
      scope '/contact/:author' do
        get '/' => :index
        post '/' => :send_mail
      end
    end
    controller :contents do
      scope '/:category_alias/:url_alias' do
        get '/' => :show, :as => :show_content
      end
    end
    controller :feed do
      scope '/' do
        get '/feed.xml' => :home, :as => :feed_home
        get '/tags/:tag/feed.xml' => :tag, :as => :feed_tag
        get '/:url_alias/feed.xml' => :category, :as => :feed_category
      end
    end
  end

  root :to => 'home#index'

  match '*path' => 'home#notfound'

end

app/models/content.rb
class Content < ActiveRecord::Base
  include Paperclip
  validates_uniqueness_of :url_alias
  validates_presence_of :url_alias, :title_it, :title_en, :content_it, :content_en, :author_id, :category_id
  validates_length_of :url_alias, :minimum => 3, :maximum => 50
  validates_format_of :url_alias, :with => /\A[a-zA-Z_\-0-9]*\z/
  before_validation :strip_fields

  belongs_to :author
  belongs_to :category
  belongs_to :image
  has_and_belongs_to_many :tags
  has_many :attachments, :dependent => :destroy

  translatable_columns :title, :content, :summary

  cattr_reader :per_page
  @@per_page = 5

  def attachments_toadd=(attachment_attributes)
    attachment_attributes.each do |attributes|
      attachments.build({ 'file' => attributes[1]})
    end
  end

  def tags_list
    ret = []
    self.tags.each { |x| ret << x.label }
    ret.join ', '
  end

  def tags_list= list
    #self.tags.destroy_all
    array = list.split ','
    nt = []
    array.each do |x| 
      nt << Tag.find_or_create(x.strip).id
    end
    self.tag_ids = nt
  end

  private
  def strip_fields
    self.title_it = self.title_it.strip unless self.title_it.nil?
    self.title_en = self.title_en.strip unless self.title_en.nil?
    self.url_alias = self.url_alias.strip unless self.url_alias.nil?
    self.summary_it = self.summary_it.strip unless self.summary_it.nil?
    self.summary_en = self.summary_en.strip unless self.summary_en.nil?
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  helper :contents
  helper_method :content_to_html

  before_filter :authenticate_author!, :except => :show
  before_filter :force_encoding, :only => [:create, :update]
  before_filter :get_content_by_id, :only => [:update, :destroy, :edit, :destroy_attachment]
  before_filter :get_content_by_alias, :only => [:show]

  respond_to :html, :xml, :js

  # GET /contents
  # GET /contents.xml
  def index
    respond_with @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.xml
  def show
    respond_with @content
  end

  # GET /contents/new
  # GET /contents/new.xml
  def new
    @content = Content.new
    @content.author = current_author
    @categories = Category.all
  end

  def new_attachment
    @attachment = Attachment.new
  end

  # GET /contents/1/edit
  def edit
    @categories = Category.all
  end

  # POST /contents
  # POST /contents.xml
  def create
    @content = Content.new(params[:content])
    @content.author = current_author

    respond_to do |format|
      if @content.save
        format.html do
          flash[:notice] = t(:notice, :scope => [:contents, :create]) 
          redirect_to show_content_path(:category_alias => @content.category.url_alias, :url_alias => @content.url_alias)
        end
        format.xml  { render :xml => @content, :status => :created, :location => @content }
      else
        @categories = Category.all
        @images = Image.all
        format.html { render :action => "new" }
        format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.xml
  def update
    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html do
          flash[:notice] = t(:notice, :scope => [:contents, :update])
          redirect_to(show_content_path :category_alias => @content.category.url_alias, :url_alias => @content.url_alias)
        end
        format.xml  { head :ok }
      else
        @categories = Category.all
        @images = Image.all
        format.html { render :action => "edit" }
        format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.xml
  def destroy
    @content.destroy
  
    respond_to do |format|
      format.html { redirect_to(contents_url) }
      format.xml  { head :ok }
    end
  end

  def destroy_attachment
    @attachment = Attachment.find params[:aid]
    if @content.attachments.include? @attachment
      @attachment.destroy
    else
      error 500
    end
  end

  def preview_content
    render :text => RedCloth.new(params[:data].force_encoding('UTF-8')).to_html
  end

  private
  def get_content_by_id
    @content = Content.find params[:id]
  end

  def get_content_by_alias
    category = Category.find :first, :conditions => ['url_alias = ?', params[:category_alias]]
    @content = Content.find :first, :conditions => ['url_alias = ? AND category_id = ?', params[:url_alias], category.id] unless category.nil?
    error 404 unless !@content.nil? && (author_signed_in? || @content.published)
  end

  def force_encoding
    params[:content][:summary_it] = params[:content][:summary_it].force_encoding('UTF-8')
    params[:content][:summary_en] = params[:content][:summary_en].force_encoding('UTF-8')
    params[:content][:content_it] = params[:content][:content_it].force_encoding('UTF-8')
    params[:content][:content_en] = params[:content][:content_en].force_encoding('UTF-8')
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag :jquery_ui %>
  <%= javascript_include_tag :mark_it_up %>
  <%= stylesheet_link_tag :jquery_ui %>
  <%= stylesheet_link_tag :mark_it_up %>
  <script type="text/javascript">
    var gallerySender;

    $(document).ready(function() {
      $("#tabs").tabs();
      $("#content_content_it").markItUp(mySettings);
      $("#content_content_en").markItUp(mySettings);
      $('#add-attach').click(function() {
        rand_id = Math.random().toString().split('.')[1];
        $('#add-attach').before('<input id="attachment_toadd_' + rand_id + '" name="content[attachments_toadd[file]]" type="file" />');
      });
      $(".gallery-browse").click(function() { gallerySender = $(this).attr("rel"); });
      $("#icon-remove-link").click(function() { $("#content_image_id").val(""); $("#icon-preview").remove(); $("#icon-remove-link").attr("style", "display: none"); return false; });
    });

    function addCategory(id, name, alias) {
      $("#content_category_id").append("<option value='" + id + "'>" + name + "</option>");
    }

    function setImage(id, name, url_thumb, url_small, url) {
      if ($("#gallery").parents(".ui-dialog").is(":visible"))
        $("#gallery").dialog('close');
      if (gallerySender == "icon") {
        $("#content_image_id").val(id);
        $("#icon-remove-link").attr("style", "");
        if ($("#icon-preview").length > 0) {
          $("#icon-preview").attr("src", url_thumb);
          $("#icon-preview").attr("alt", name);
        } else {
          $("#content_image_id").after("<img id='icon-preview' src='" + url_thumb + "' alt='" + name + "' />");
        }
      } else if (gallerySender == "markitup")
        $.markItUp({ replaceWith: '!' + url + '(' + name + ')!'});
    }
  </script>
<% end -%>

<%= form_for(@content, :html => { :multipart => true }) do |f| %>
  <% if @content.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>
    <ul>
    <% @content.errors.full_messages.each do |msg| %>
      <li><%= raw msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <fieldset>
    <legend><%= t(:section_general) %></legend>
    <div class="field">
      <%= f.label :author %><br />
      <%= f.text_field :author, :disabled => 'true' %>
    </div>
    <div class="field">
      <%= f.label :category, Category.model_name.human %><br />
      <%= f.collection_select :category_id, @categories, :id, :label %>
      <%= link_to t(:title, :scope => [:categories, :new]), new_category_path, :remote => true %>
    </div>
    <div class="field">
      <%= f.label :url_alias %><br />
      <%= f.text_field :url_alias, :maxlength => 50 %>
    </div>
    <div class="flaglist">
      <div class="field">
        <%= f.label :published %><br />
        <%= f.check_box :published %>
      </div>
      <div class="field">
        <%= f.label :has_comments %><br />
        <%= f.check_box :has_comments %>
      </div>
      <div class="field">
        <%= f.label :in_home %><br />
        <%= f.check_box :in_home %>
      </div>
    </div>
    <div class="field" style="clear: both;">
      <%= f.label :image %><br/>
      <%= f.hidden_field :image_id %>
      <%= image_tag(@content.image.url(:thumb), :id => 'icon-preview') unless @content.image.nil? %>
      <%= link_to t(:browse), :images, :remote => true, :id => "icon-browse-link", :class => "gallery-browse", :rel => 'icon' %>
      <%= link_to t(:remove), '#', :id => "icon-remove-link", :style => (@content.image.nil? ? "display: none;" : "") %>
    </div>
    <div class="field">
      <%= f.label :tags %><br />
      <%= f.text_field :tags_list %>
    </div>
  </fieldset>

  <div id="tabs">
    <ul>
      <li class="tab"><a href="#it"><span><%= t :it, :scope => :languages %></span></a></li>
      <li class="tab"><a href="#en"><span><%= t :en, :scope => :languages %></span></a></li>
    </ul>
    <div id="it">
      <div class="field">
        <%= f.label :title_it, t(:title, :scope => :attributes) %><br />
        <%= f.text_field :title_it %>
      </div>
      <div class="field">
        <%= f.label :summary_it, t(:summary, :scope => :attributes) %><br />
        <%= f.text_area :summary_it, :cols => 80, :rows => 2 %>
      </div>
      <div class="field">
        <%= f.label :content_it, t(:content, :scope => :attributes) %><br />
        <%= f.text_area :content_it %>
      </div>
    </div>
    <div id="en">
      <div class="field">
        <%= f.label :title_en, t(:title, :scope => :attributes) %><br />
        <%= f.text_field :title_en %>
      </div>
      <div class="field">
        <%= f.label :summary_en, t(:summary, :scope => :attributes) %><br />
        <%= f.text_area :summary_en, :cols => 80, :rows => 2 %>
      </div>
      <div class="field">
        <%= f.label :content_en, t(:content, :scope => :attributes) %><br />
        <%= f.text_area :content_en %>
      </div>
    </div>
  </div>
  <fieldset id="attachments">
    <legend><%= t(:attachment_mgr) %></legend>
    <ul>
      <% @content.attachments.each do |a| %>
        <li id="attachment_<%= a.id %>"><%= a.file_file_name %> (<%= link_to t(:link_destroy), content_destroy_attachment_path(:id => @content.id, :aid => a.id), :method => :delete, :remote => true %>)</li>
      <% end -%>
    </ul>
    <%= link_to t(:attachment_add), contents_add_attachment_path, :remote => true, :id => 'add_attachment' %>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= render :partial => 'categories/jsform', :locals => { :category => Category.new } %>
<%= render :partial => 'images/jsform' %>

app/views/contents/_list.html.erb
<div id="post-list">
  <% posts.each do |p| %>
    <div class="post_item">
      <%= image_tag(p.image.url(:thumb), :class => 'contenticon') unless p.image.nil? %>
      <div class="title-box"><h2 class="title"><%= link_to p.title, show_content_path({:category_alias => p.category.url_alias, :url_alias => p.url_alias}) %></h2></div>
      <div class="meta">
        <div class="submitted">
          <%= t :created_at, :scope => :attributes %> <%= l p.created_at, :format => :medium %>
          <% unless p.created_at == p.updated_at %>
            - <%= t :updated_at, :scope => :attributes %> <%= l p.updated_at, :format => :medium %>
          <% end -%>
        </div>
        <%= render :partial => 'tags/list', :locals => {:tags => p.tags.order("label_#{I18n.locale}")} %>
      </div>
      <div class="summary"><p><%= raw p.summary %></p></div>
      <div class="post-actions">
        <%= link_to t(:read_all), show_content_path({:category_alias => p.category.url_alias, :url_alias => p.url_alias}) %>
        <% if p.has_comments %>
          <%= id_comments_link p, :url => show_content_path({:category_alias => p.category.url_alias, :url_alias => p.url_alias}), :acct_no => ID_ACCT_NO_I18N.has_key?(I18n.locale) ? ID_ACCT_NO_I18N[I18n.locale] : ID_ACCT_NO %>
        <% end -%>
      </div>
    </div>
  <% end -%>
  <%= will_paginate posts %>
</div>

app/views/contents/add_attachment.js.erb
rand_id = Math.random().toString().split('.')[1];
$('#add_attachment').before('<input type="file" name="content[attachments_toadd[' + rand_id + ']]" />');

app/views/contents/destroy_attachment.js.erb
$('#attachment_<%= @attachment.id %>').remove();

app/views/contents/edit.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:link_show), show_content_path(:category_alias => @content.category.url_alias, :url_alias => @content.url_alias) %> |
<%= link_to t(:back), contents_path %>

app/views/contents/index.html.erb
<% title t('.title') %>

<table>
  <tr>
    <th><%= t :title, :scope => :attributes %></th>
    <th><%= t :author, :scope => :attributes %></th>
    <th><%= Category.model_name.human %></th>
    <th><%= t :published, :scope => :attributes %></th>
    <th><%= t :in_home, :scope => :attributes %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= content.title %></td>
    <td><%= content.author %></td>
    <td><%= content.category %></td>
    <td><%= content.published %></td>
    <td><%= content.in_home %></td>
    <td><%= link_to t(:link_show), show_content_path({:category_alias => content.category.url_alias, :url_alias => content.url_alias}) %></td>
    <td><%= link_to t(:link_edit), edit_content_path(content) %></td>
    <td><%= link_to t(:link_destroy), content, :confirm => t(:confirm_sure), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:title, :scope => [:contents, :new]), new_content_path %>

app/views/contents/new.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:back), contents_path %>

app/views/contents/show.html.erb
<% if @content.image.nil? %>
  <% title @content.title %>
<% else %>
  <% title @content.title, false %>
  <h1><%= image_tag(@content.image.url(:thumb), :id => 'icontitle', :class => 'contenticon') %> <%= @content.title %></h1>
<% end -%>

<% meta_description(@content.summary) unless @content.summary.blank? %>

<div class="post_show <%='unpublished' if !@content.published -%>">
  <div class="meta">
    <div class="submitted">
      <%= t :created_at, :scope => :attributes %> <%= l @content.created_at, :format => :medium %>
      <% unless @content.created_at == @content.updated_at -%>
        - <%= t :updated_at, :scope => :attributes %> <%= l @content.updated_at, :format => :medium %>
      <% end -%>
    </div>
    <%= render :partial => 'tags/list', :locals => { :tags => @content.tags.order("label_#{I18n.locale}") } %>
  </div>
  <% unless @content.summary.nil? || @content.summary.empty? %>
    <div class="summary"><p><%= raw @content.summary %></p></div>
  <% end -%>
  <div class="content"><%= raw RedCloth.new(@content.content).to_html %></div>
  <div class="content-separator">&nbsp;</div>
  <% unless @content.attachments.empty? %>
    <div class="attachments">
      <h4><%= t :attachment_mgr %></h4>
      <ul>
      <% @content.attachments.each do |a| %>
        <li><%= link_to a.file_file_name, a.file.url %></li>
      <% end -%>
      </ul>
    </div>
  <% end -%>
  <% if @content.has_comments %>
    <%= id_comments @content, :title => @content.title, :url => show_content_path(:category_alias => @content.category.url_alias, :url_alias => @content.url_alias, :only_path => false), :acct_no => ID_ACCT_NO_I18N.has_key?(I18n.locale) ? ID_ACCT_NO_I18N[I18n.locale] : ID_ACCT_NO %>
  <% end -%>
</div>

<% if author_signed_in? %>
  <div id="content-actions">
    <%= link_to t(:link_edit), edit_content_path(@content) %> 
    <%= link_to t(:back), contents_path %>
  </div>
<% end -%>