config/routes.rb
Nrblog::Application.routes.draw do |map|
  devise_for :authors, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  scope '(/:locale)', :constraints => { :locale => /\w{2}/ } do
    controller :home do
      get '/' => :index, :as => :index
    end

    controller :sitemap do
      get '/sitemap.xml' => :index, :as => :sitemap
    end

    scope '/admin' do
      resources :categories, :except => :show
      resources :menu_items, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :images
      resources :blocks, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :tags, :except => :show
      resources :contents, :except => :show do
        delete '/:aid' => :destroy_attachment, :as => :destroy_attachment, :on => :member
        get '/add_attachment' => :add_attachment, :as => :add_attachment, :on => :collection
        post '/preview' => :preview_content, :as => :preview_content, :on => :collection
      end
    end

    controller :categories do
      scope '/' do
        get '/:url_alias' => :show, :as => :show_category
      end
    end
    controller :tags do
      scope '/tags' do
        get '/:tag' => :show, :as => :show_tag
      end
    end
    controller :contact do
      scope '/contact/:author' do
        get '/' => :index
        post '/' => :send_mail
      end
    end
    controller :contents do
      scope '/:category_alias/:url_alias' do
        get '/' => :show, :as => :show_content
      end
    end
    controller :feed do
      scope '/' do
        get '/feed.xml' => :home, :as => :feed_home
        get '/tags/:tag/feed.xml' => :tag, :as => :feed_tag
        get '/:url_alias/feed.xml' => :category, :as => :feed_category
      end
    end
  end

  root :to => 'home#index'

  match '*path' => 'home#notfound'

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  translatable_columns :title
  validates_presence_of :title_it, :title_en, :menu_type, :url, :menu_order
  before_validation :fill_empty_i18n, :strip_fields, :set_default_position
  validates_inclusion_of :menu_type, :in => %w(horizontal_top vertical_right)
  validates_numericality_of :menu_order

  private
  def strip_fields
    self.title_it = self.title_it.strip unless self.title_it.nil?
    self.title_en = self.title_en.strip unless self.title_en.nil?
    self.url = self.url.strip unless self.url.nil?
  end
  
  def fill_empty_i18n
    if self.title_it.blank? && !self.title_en.blank?
      self.title_it = self.title_en
    elsif self.title_en.blank? && !self.title_it.blank?
      self.title_en = self.title_it
    end
  end

  def set_default_position
    if self.menu_order.nil?
      fb = MenuItem.find(:first, :conditions => ['menu_type = ?', self.menu_type], :order => 'menu_order DESC')
      self.menu_order = fb.nil? ? 0 : fb.menu_order + 1
    end
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_filter :authenticate_author!
  before_filter :get_menu_item, :only => [ :destroy, :update, :edit, :change_order, :change_type ]

  respond_to :html

  # GET /menu_items
  # GET /menu_items.xml
  def index
    items = MenuItem.find(:all, :order => 'menu_order ASC')
    @menu_items = {}
    items.each do |item|
      sype = item.menu_type.to_sym
      @menu_items[sype] = [] if @menu_items[sype].nil?
      @menu_items[sype] << item
    end
    respond_with @menu_items
  end

  def show
    error 404
  end

  # GET /menu_items/new
  # GET /menu_items/new.xml
  def new
    @menu_item = MenuItem.new
    respond_with @menu_item
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.xml
  def create
    @menu_item = MenuItem.new(params[:menu_item])
    
    if @menu_item.save
      flash[:notice] = t :notice, :scope => [:menu_items, :create]
      redirect_to menu_items_url
    else
      render :action => :new
    end
  end

  # PUT /menu_items/1
  # PUT /menu_items/1.xml
  def update
    if @menu_item.update_attributes(params[:menu_item])
      flash[:notice] = t :notice, :scope => [:menu_items, :update]
      redirect_to menu_items_url
    else
      render :action => :edit
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.xml
  def destroy
    @menu_item.destroy

    redirect_to(menu_items_url)
  end

  def change_order
    errors = {}
    old_pos = @menu_item.menu_order
    new_pos = params[:new_pos].to_i

    subset = MenuItem.find(:all, :conditions => ['menu_type = ?', @menu_item.menu_type], :order => 'menu_order ASC')
    subset[(old_pos + 1)..new_pos].each { |item| item.menu_order -= 1 } if new_pos > old_pos
    subset[new_pos..(old_pos - 1)].each { |item| item.menu_order += 1 } if new_pos < old_pos
    @menu_item.menu_order = new_pos
    subset.each do |item| 
      item.save
      errors[item.title] = item.errors if item.errors.any?
    end
    @menu_item.save
    errors[@menu_item.title] = @menu_item.errors if @menu_item.errors.any?

    render :text => errors.any? ? errors : 'OK'
  end

  def change_type
    errors = {}
    new_type = params[:new_type]

    old_subset = MenuItem.find(:all, :conditions => ['menu_type = ? AND menu_order > ?', @menu_item.menu_type, @menu_item.menu_order])
    old_subset.each do |item|
      item.menu_order -= 1
      item.save
      errors[item.title] = item.errors if item.errors.any?
    end

    @menu_item.menu_type = new_type
    new_subset = MenuItem.find(:first, :conditions => ['menu_type = ?', new_type], :order => 'menu_order DESC')
    @menu_item.menu_order = new_subset.nil? ? 0 : new_subset.menu_order + 1
    @menu_item.save
    errors[@menu_item.title] = @menu_item.errors if @menu_item.errors.any?

    render :text => errors.any? ? errors : 'OK'
  end

  private
  def get_menu_item
    @menu_item = MenuItem.find(params[:id])
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
  def available_menu_types
    return [ :horizontal_top, :vertical_right ]
  end

  def enabled_top_horizontal_menu_items
    return MenuItem.find :all, :conditions => 'menu_type = \'horizontal_top\'', :order => 'menu_order ASC'
  end

  def enabled_vertical_right_menu_items
    return MenuItem.find :all, :conditions => 'menu_type = \'vertical_right\'', :order => 'menu_order ASC'
  end
end

app/views/menu_items/_form.html.erb
<% content_for :head do -%>
  <%= javascript_include_tag :jquery_ui %>
  <%= stylesheet_link_tag :jquery_ui %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#tabs").tabs();
    });
  </script>
<% end -%>

<%= form_for(@menu_item) do |f| %>
  <% if @menu_item.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>
    <ul>
    <% @menu_item.errors.full_messages.each do |msg| %>
      <li><%= raw msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_type, t(:type, :scope => :attributes) %><br />
    <%= f.select :menu_type, options_for_select(available_menu_types) %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div id="tabs">
    <ul>
      <li class="tab"><a href="#it"><span><%= t :it, :scope => :languages %></span></a></li>
      <li class="tab"><a href="#en"><span><%= t :en, :scope => :languages %></span></a></li>
    </ul>
    <div id="it">
      <div class="field">
        <%= f.label :title_it, t(:title, :scope => :attributes) %><br />
        <%= f.text_field :title_it %>
      </div>
    </div>
    <div id="en">
      <div class="field">
        <%= f.label :title_en, t(:title, :scope => :attributes) %><br />
        <%= f.text_field :title_en %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:back), menu_items_path %>

app/views/menu_items/index.html.erb
<% title t('.title') %>

<% content_for :head do %>
  <%= stylesheet_link_tag :jquery_ui %>
  <%= javascript_include_tag :jquery_ui %>
  <style type="text/css">
    .connectedSortable li { margin: 0 5px 5px 5px; padding: 5px; width: 160px; }
    .connectedSortable li img { float: right; }
  </style>
  <script type="text/javascript">
    $(document).ready(function() {
      $(".connectedSortable").sortable({
        update: function(event, ui) {
          showStatus(50, 'Sending data ...');
          $.ajax({
            type: 'POST',
            url: '<%= menu_items_change_order_path %>',
            data: { id: ui.item.attr("id").substring(1), new_pos: $(ui.item).parent().children().index($(ui.item)) },
            success: function() {
              hideStatus();
            }
          });
        }
      }).disableSelection();

      var $tabs = $("#menu-tabs").tabs();

      var $tab_items = $("ul:first li", $tabs).droppable({
        accept: ".connectedSortable li",
        hoverClass: "ui-state-hover",
        drop: function(ev, ui) {
          var $item = $(this);
          var $list = $($item.find('a').attr('href')).find('.connectedSortable');

          ui.draggable.hide('slow', function() {
            $tabs.tabs('select', $tab_items.index($item));
            $(this).appendTo($list).show('slow');
            showStatus(50, 'Sending data ...');
            $.ajax({
              type: 'POST',
              url: '<%= menu_items_change_type_path %>',
              data: { id: $(this).attr("id").substring(1), new_type: $($list).attr("id") },
              success: function() {
                hideStatus();
              }
            });
          });
        }
      });
    });
  </script>
<% end -%>

<%= render :partial => 'common/progress' %>

<div id="menu-tabs">
  <ul>
    <% available_menu_types.each do |type| %>
      <li class="tab"><a href="#tab-<%= type %>"><%= type %></a></li>
    <% end -%>
  </ul>
  <% available_menu_types.each do |type| %>
    <div id="tab-<%= type %>">
      <ul id="<%= type %>" class="connectedSortable ui-helper-reset">
        <% @menu_items[type].each do |item| %>
          <li class="ui-state-default" id="m<%= item.id %>"><%= item.title %> <%= link_to remove_icon, item, :confirm => t(:confirm_sure), :method => :delete %> <%= link_to edit_icon, edit_menu_item_path(item) %></li>
        <% end unless @menu_items[type].nil? -%>
      </ul>
    </div>
  <% end -%>
</div>

<br />

<%= link_to t(:title, :scope => [:menu_items, :new]), new_menu_item_path %> | <%= refresh_link %>

app/views/menu_items/new.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:back), menu_items_path %>