config/routes.rb
Nrblog::Application.routes.draw do |map|
  devise_for :authors, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  scope '(/:locale)', :constraints => { :locale => /\w{2}/ } do
    controller :home do
      get '/' => :index, :as => :index
    end

    controller :sitemap do
      get '/sitemap.xml' => :index, :as => :sitemap
    end

    scope '/admin' do
      resources :categories, :except => :show
      resources :menu_items, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :images
      resources :blocks, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :tags, :except => :show
      resources :contents, :except => :show do
        delete '/:aid' => :destroy_attachment, :as => :destroy_attachment, :on => :member
        get '/add_attachment' => :add_attachment, :as => :add_attachment, :on => :collection
        post '/preview' => :preview_content, :as => :preview_content, :on => :collection
      end
    end

    controller :categories do
      scope '/' do
        get '/:url_alias' => :show, :as => :show_category
      end
    end
    controller :tags do
      scope '/tags' do
        get '/:tag' => :show, :as => :show_tag
      end
    end
    controller :contact do
      scope '/contact/:author' do
        get '/' => :index
        post '/' => :send_mail
      end
    end
    controller :contents do
      scope '/:category_alias/:url_alias' do
        get '/' => :show, :as => :show_content
      end
    end
    controller :feed do
      scope '/' do
        get '/feed.xml' => :home, :as => :feed_home
        get '/tags/:tag/feed.xml' => :tag, :as => :feed_tag
        get '/:url_alias/feed.xml' => :category, :as => :feed_category
      end
    end
  end

  root :to => 'home#index'

  match '*path' => 'home#notfound'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  translatable_columns :label
  validates :label_it, :presence => true, :uniqueness => true
  validates :label_en, :presence => true, :uniqueness => true
  validates :url_alias, :presence => true, :uniqueness => true
  validate :unique_labels_between_locales
  has_and_belongs_to_many :contents
  before_validation :fill_empty_i18n, :strip_fields, :generate_url_alias

  def Tag.find_or_create label
    tag = Tag.find(:first, :conditions => ['label_it like ? OR label_en like ?', label, label])
    if tag.nil?
      tag = Tag.new
      tag.label = label
      tag.save
    end
    return tag
  end

  private
  def unique_labels_between_locales
    if self.id.nil?
      tag = Tag.find :first, :conditions => ['label_it like ?', self.label_en]
    else
      tag = Tag.find :first, :conditions => ['label_it like ? AND id != ?', self.label_en, self.id]
    end
    self.errors.add(:label_en, I18n.t('errors.messages.unique_label_between_locales')) unless tag.nil?
    if self.id.nil?
      tag = Tag.find :first, :conditions => ['label_en like ?', self.label_it]
    else
      tag = Tag.find :first, :conditions => ['label_en like ? AND id != ?', self.label_it, self.id]
    end
    self.errors.add(:label_it, I18n.t('errors.messages.unique_label_between_locales')) unless tag.nil?
  end

  def generate_url_alias
    if self.url_alias.blank? && !self.label.blank?
      self.url_alias = label.gsub(/ /, '_').gsub(/\./,'_').downcase
    end
  end

  def fill_empty_i18n
    if self.label_it.blank? && !self.label_en.blank?
      self.label_it = self.label_en
    elsif self.label_en.blank? && !self.label_it.blank?
      self.label_en = self.label_it
    end
  end

  def strip_fields
    self.label_it = self.label_it.strip unless self.label_it.nil?
    self.label_en = self.label_en.strip unless self.label_en.nil?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_author!, :except => [:show]
  before_filter :get_tag, :only => [:edit, :update, :destroy]

  respond_to :html
 
  # GET /tags
  # GET /tags.xml
  def index
    respond_with @tags = Tag.all
  end

  def show
    @tag = Tag.find :first, :conditions => ['url_alias = ?', params[:tag]]
    unless @tag.nil?
      @posts = Content.paginate :per_page => 5, :page => params[:page], :conditions => ['published = 1 AND id IN (SELECT content_id FROM contents_tags WHERE tag_id = ?)', @tag.id], :order => 'created_at DESC'
    else
      error 404
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    respond_with @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    if @tag.save
      flash[:notice] = t :notice, :scope => [:tags, :create]
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    if @tag.update_attributes(params[:tag])
      flash[:notice] = t :notice, :scope => [:tags, :update]
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag.destroy
    redirect_to :action => :index
  end

  private
  def get_tag
    @tag = Tag.find params[:id]
  end
end

app/helpers/tags_helper.rb
module TagsHelper

end

app/views/tags/_form.html.erb
<% content_for :head do -%>
  <%= javascript_include_tag :jquery_ui %>
  <%= stylesheet_link_tag :jquery_ui %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#tabs").tabs();
    });
  </script>
<% end -%>

<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
    <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= raw msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <p><%= f.label :url_alias %><br/>
    <%= f.text_field :url_alias %></p>
  </div>

  <div id="tabs">
    <ul>
      <li class="tab"><a href="#it"><span><%= t :it, :scope => :languages %></span></a></li>
      <li class="tab"><a href="#en"><span><%= t :en, :scope => :languages %></span></a></li>
    </ul>
    <div id="it">
      <div class="field">
        <%= f.label :label_it, t(:label, :scope => :attributes) %><br />
        <%= f.text_field :label_it %>
      </div>
    </div>
    <div id="en">
      <div class="field">
        <%= f.label :label_en, t(:label, :scope => :attributes) %><br />
        <%= f.text_field :label_en %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_list.html.erb
<% unless tags.empty? %>
  <div class="taglist clear-inline">
    <%= t '.in' %>
    <ul class="links clear-inline">
      <% tags.each do |t| %>
        <li class="tag"><%= link_to t.label, show_tag_path({:tag => t.url_alias}), :rel => 'tag' %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

app/views/tags/edit.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:back), tags_path %>

app/views/tags/index.html.erb
<% title t('.title') %>

<table>
  <tr>
    <th><%= t :label, :scope => :attributes %></th>
    <th><%= t :url_alias, :scope => :attributes %></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.label %></td>
    <td><%= link_to show_tag_path(:tag => tag.url_alias, :locale => nil), show_tag_path(:tag => tag.url_alias) %></td>
    <td><%= link_to t(:link_edit), edit_tag_path(tag) %></td>
    <td><%= link_to t(:link_destroy), tag, :confirm => t(:confirm_sure), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:title, :scope => [:tags, :new]), new_tag_path %>

app/views/tags/new.html.erb
<% title t('.title') %>

<%= render 'form' %>

<%= link_to t(:back), tags_path %>

app/views/tags/show.html.erb
<% title @tag.label %>

<div class="fright">
  <%= feed_icon feed_tag_path({:tag => @tag.url_alias}) %>
</div>

<% unless @tag.contents.empty? %>
  <%= render :partial => 'contents/list', :locals => { :posts => @posts } %>
  <%= will_paginate @posts %>
<% else %>
  <%= t('.empty') %>
<% end -%>