config/routes.rb
Nrblog::Application.routes.draw do |map|
  devise_for :authors, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  scope '(/:locale)', :constraints => { :locale => /\w{2}/ } do
    controller :home do
      get '/' => :index, :as => :index
    end

    controller :sitemap do
      get '/sitemap.xml' => :index, :as => :sitemap
    end

    scope '/admin' do
      resources :categories, :except => :show
      resources :menu_items, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :images
      resources :blocks, :except => :show do
        post '/change_order' => :change_order, :as => :change_order, :on => :collection
        post '/change_type' => :change_type, :as => :change_type, :on => :collection
      end
      resources :tags, :except => :show
      resources :contents, :except => :show do
        delete '/:aid' => :destroy_attachment, :as => :destroy_attachment, :on => :member
        get '/add_attachment' => :add_attachment, :as => :add_attachment, :on => :collection
        post '/preview' => :preview_content, :as => :preview_content, :on => :collection
      end
    end

    controller :categories do
      scope '/' do
        get '/:url_alias' => :show, :as => :show_category
      end
    end
    controller :tags do
      scope '/tags' do
        get '/:tag' => :show, :as => :show_tag
      end
    end
    controller :contact do
      scope '/contact/:author' do
        get '/' => :index
        post '/' => :send_mail
      end
    end
    controller :contents do
      scope '/:category_alias/:url_alias' do
        get '/' => :show, :as => :show_content
      end
    end
    controller :feed do
      scope '/' do
        get '/feed.xml' => :home, :as => :feed_home
        get '/tags/:tag/feed.xml' => :tag, :as => :feed_tag
        get '/:url_alias/feed.xml' => :category, :as => :feed_category
      end
    end
  end

  root :to => 'home#index'

  match '*path' => 'home#notfound'

end

app/models/category.rb
class Category < ActiveRecord::Base
  translatable_columns :label
  validates_presence_of :label_en, :label_it, :url_alias
  validates_uniqueness_of :url_alias, :label_en, :label_it
  before_validation :fill_empty_i18n, :strip_fields
  validates_length_of :url_alias, :minimum => 3, :maximum => 50
  validates_format_of :url_alias, :with => /\A[a-zA-Z_\-0-9]*\z/
  validates_exclusion_of :url_alias, :in => %w(404.html 422.html 500.html favicon.ico _images_ javascripts _markitup_ robots.txt stylesheets system)

  has_many :contents, :dependent => :destroy

  def to_s
    self.label
  end

  private
  def strip_fields
    self.label_en = self.label_en.strip unless self.label_en.nil?
    self.label_it = self.label_it.strip unless self.label_it.nil?
    self.url_alias = self.url_alias.strip unless self.url_alias.nil?
  end

  def fill_empty_i18n
    if self.label_en.blank? && !self.label_it.blank?
      self.label_en = self.label_it
    elsif self.label_it.blank? && !self.label_en.blank?
      self.label_it = self.label_en
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_author!, :except => :show
  before_filter :get_category, :only => [:edit, :update, :destroy]

  respond_to :html, :js, :xml

  # GET /categories
  # GET /categories.xml
  def index
    respond_with(@categories = Category.all)
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find :first, :conditions => ['url_alias = ?', params[:url_alias]]
    unless @category.nil?
      @posts = Content.paginate :page => params[:page], :conditions => ['published = 1 AND category_id = ?', @category.id], :order => 'created_at DESC'
      render :show
    else
      error 404
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    respond_with(@category = Category.new)
  end

  # GET /categories/1/edit
  def edit
    respond_with @category
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { flash[:notice] = t(:notice, :scope => [:categories, :create]); redirect_to :action => :index; }
        format.js { render 'create' }
      else
        format.html { render :action => :new }
        format.js { render 'showerrors' }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    respond_to do |format|
      if @category.update_attributes params[:category]
        format.html { flash[:notice] = t(:notice, :scope => [:categories, :update]); redirect_to :action => :index; }
      else
        format.html { render :action => :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category.destroy

    redirect_to(categories_url)
  end

  private
  def get_category
    @category = Category.find params[:id]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%# JS: $("#category-tabs").tabs() should be added to the invoking view to show tabs %>

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= raw msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :url_alias %><br />
    <%= f.text_field :url_alias, :maxlength => 40 %>
  </div>

  <div id="category-tabs">
    <ul>
      <li class="tab"><a href="#category-it"><span><%= t :it, :scope => :languages %></span></a></li>
      <li class="tab"><a href="#category-en"><span><%= t :en, :scope => :languages %></span></a></li>
    </ul>
    <div id="category-it">
      <div class="field">
        <%= f.label :label_it, t(:label, :scope => :attributes) %><br />
        <%= f.text_field :label_it %>
      </div>
    </div>
    <div id="category-en">
      <div class="field">
        <%= f.label :label_en, t(:label, :scope => :attributes) %><br />
        <%= f.text_field :label_en %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_jsform.html.erb
<div style="display: none">
  <div id="add-category" title="<%= t(:title, :scope => [:categories, :new]) %>">
    <div id="category-errors"></div>
    <% @category = category %>
    <%= render :partial => 'categories/form' %>
  </div>
</div>

app/views/categories/create.js.erb
addCategory('<%= @category.id %>', '<%= @category.label.gsub("'", "\\'") %>', '<%= show_category_path(@category.url_alias) %>');
$("#add-category").dialog('close');

app/views/categories/created.js.erb
addCategory('<%= @category.id %>', '<%= @category.label %>', '<%= show_category_path(@category.url_alias) %>');
$("#add-category").dialog('close');

app/views/categories/edit.html.erb
<% title t('.title') %>

<% content_for :head do -%>
  <%= javascript_include_tag :jquery_ui %>
  <%= stylesheet_link_tag :jquery_ui %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#category-tabs").tabs();
    });
  </script>
<% end -%>

<%= render 'form' %>

<%= link_to t(:back), categories_path %>

app/views/categories/index.html.erb
<% title t('.title') %>

<table id="categories-list">
  <tr>
    <th><%= t :label, :scope => :attributes %></th>
    <th><%= t :url_alias, :scope => :attributes %></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.label %></td>
    <td><%= link_to show_category_path({:locale => nil, :url_alias => category.url_alias}), show_category_path({:url_alias => category.url_alias}) %>/</td>
    <td><%= link_to t(:link_edit), edit_category_path(category) %></td>
    <td><%= link_to t(:link_destroy), category, :confirm => t(:confirm_sure), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:title, :scope => [:categories, :new]), new_category_path %>

app/views/categories/new.html.erb
<% title t('.title') %>

<% content_for :head do -%>
  <%= javascript_include_tag :jquery_ui %>
  <%= stylesheet_link_tag :jquery_ui %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#category-tabs").tabs();
    });
  </script>
<% end -%>

<%= render 'form' %>

<%= link_to t(:back), categories_path %>

app/views/categories/new.js.erb
$("#new_category").clearForm();
$("#category-errors").empty();
$("#add-category").dialog({
  width: 360,
  modal: true,
  buttons: {
    '<%= t(:category_new) %>': function() {
      $("#new_category").submit();
    },
    '<%= t(:back) %>': function() {
      $(this).dialog('close');
    }
  },
  close: function() { }
});
$("#new_category").attr("data-remote", "true");
$("#category_submit").attr("style", "display: none");
$("#category-tabs").tabs();

app/views/categories/show.html.erb
<% title @category.label %>

<div class="fright">
  <%= feed_icon feed_category_path({:url_alias => @category.url_alias}) %>
</div>

<% unless @category.contents.empty? %>
  <%= render :partial => 'contents/list', :locals => { :posts => @posts } %>
  <%= will_paginate @posts %>
<% else %>
  <%= t('.empty') %>
<% end -%>

app/views/categories/showerrors.js.erb
$("#category-errors").empty();
<% @category.errors.each do |field, msg| %>
  $("#category-errors").append("<p class='alert'><%= t("attributes.#{field}") %>: <%= raw(msg) %></p>");
<% end -%>